version: '3.8'

services:
  bot:
    build: .
    container_name: whatsapp-credential-bot
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://botuser:botpass@db:5432/whatsapp_bot
      ENCRYPTION_KEY: supersecretkey
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: whatsapp-postgres
    environment:
      POSTGRES_DB: whatsapp_bot
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  pgdata:
